import = [
    "~/.config/alacritty/themes/alacritty_0_12.toml"
]

[window]
decorations = "None"
opacity = 0.9
startup_mode = "Maximized"

[font]
size = 14
normal = { family = "HackNerdFont", style = "Regular" }
bold = { family = "HackNerdFont", style = "Bold" }
italic = { family = "HackNerdFont", style = "Italic" }
bold_italic = { family = "HackNerdFont", style = "BoldItalic" }
